services:
  web:
    build: .
    ports:
      - "80:8000"
    volumes:
      # This isolates JUST the database so your saves are permanent
      - ./db.sqlite3:/app/db.sqlite3
    # This ensures your site boots back up if the EC2 server restarts
    restart: always
    environment:
      # --- The Security Lockdown ---
      - DEBUG=False
      - ALLOWED_HOSTS=44.255.117.28,localhost
      - DJANGO_SECRET_KEY=MakeUpARandomLongStringOfTextHere123456789!
      # --- The API Keys ---
      - TMDB_API_KEY=your_actual_tmdb_key_here
      - GOOGLE_BOOKS_KEY=your_actual_google_key_here
      - TWITCH_CLIENT_ID=your_actual_twitch_id_here
      - TWITCH_CLIENT_SECRET=your_actual_twitch_secret_here