version: '3.8'
services:
  web:
    build: .
    ports:
      - "80:8000"
    volumes:
      # This isolates JUST the database so your saves are permanent
      - ./db.sqlite3:/app/db.sqlite3
    # This ensures your site boots back up if the EC2 server restarts
    restart: always