# Generated by Django 6.0.3 on 2026-03-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('creator', models.CharField(help_text='Author, Director, or Studio', max_length=255)),
                ('media_type', models.CharField(choices=[('Book', 'Book'), ('Movie', 'Movie'), ('Game', 'Game')], max_length=10)),
                ('status', models.CharField(choices=[('Backlog', 'Backlog'), ('In-Progress', 'In-Progress'), ('Finished', 'Finished')], default='Backlog', max_length=15)),
                ('priority_flag', models.BooleanField(default=False, help_text='Highlight for Next Up')),
                ('rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
