# Generated by Django 6.0.3 on 2026-03-31 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='media_type',
            field=models.CharField(choices=[('Book', 'Book'), ('Movie', 'Movie'), ('Game', 'Game'), ('Other', 'Other')], max_length=10),
        ),
    ]
