# Generated by Django 6.0.3 on 2026-04-19 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_mediaitem_media_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='creator',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='media_type',
            field=models.CharField(choices=[('Game', 'Game'), ('Book', 'Book'), ('Movie', 'Movie'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='priority_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='status',
            field=models.CharField(choices=[('Backlog', 'Backlog'), ('In-Progress', 'In-Progress'), ('Finished', 'Finished')], default='Backlog', max_length=20),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
