# Generated by Django 6.0.3 on 2026-04-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_mediaitem_user_alter_mediaitem_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
