# Generated by Django 6.0.3 on 2026-04-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_mediaitem_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
