# Generated by Django 6.0.3 on 2026-04-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_mediaitem_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='queue_order',
            field=models.IntegerField(default=0),
        ),
    ]
