# Generated by Django 6.0.3 on 2026-04-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_mediaitem_cover_image_url_alter_mediaitem_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='media_type',
            field=models.CharField(choices=[('Book', 'Book'), ('Movie', 'Movie/TV'), ('Game', 'Game'), ('Other', 'Other')], max_length=20),
        ),
    ]
